import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>          
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="/login"
            className={styles.card}       
          >
            <h2>
              Log In <span>-&gt;</span>
            </h2>
            <p>
              Log in to view protected routes!
            </p>
          </a>

          <a
            href="/signup"
            className={styles.card}          
          >
            <h2>
              Sign Up <span>-&gt;</span>
            </h2>
            <p>
              No account? Sign up for one here to view protected routes!
            </p>
          </a>

          <a
            href="/protected"
            className={styles.card}
          >
            <h2>
              View Protected Routes <span>-&gt;</span>
            </h2>
            <p>
              If you are logged in, you can view the protected route here!
            </p>
          </a>

          <a
            href="/logout"
            className={styles.card}           
          >
            <h2>
              Log Out <span>-&gt;</span>
            </h2>
            <p>
              Log out of your account! You will not longer be able to view the protected routes after this!
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
